import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { Navigation } from "@/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex p-10"> 
        {/* <div className="flex-none w-28 h-16"> <Navigation /></div>        */}
        <div className="flex-grow h-16">  {children} </div>    
        </div>
      </body>
    </html>
  );
}
